---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/store":
    get:
      summary: Retrieves all stores
      tags:
      - Stores
      responses:
        '200':
          description: store found
          content:
            application/json:
              example:
                status_code: 0
                stores:
                - id: 1
                  merchant_id: '9999999'
                  store_id: '1'
                  name: 街口測試1
                  pos_id: '1'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
                - id: 2
                  merchant_id: '9999999'
                  store_id: '2'
                  name: 街口測試2
                  pos_id: '2'
                  created_at: '2021-08-21T22:47:53.517Z'
                  updated_at: '2021-08-21T22:47:53.517Z'
    post:
      summary: Create a store
      tags:
      - Stores
      parameters: []
      responses:
        '200':
          description: store created
          content:
            application/json:
              example:
                status_code: 0
                store:
                  id: 1
                  merchant_id: '9999999'
                  name: 街口測試1
                  pos_id: '1'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_id:
                  type: string
                name:
                  type: string
                pos_id:
                  type: string
              required:
              - merchant_id
              - name
              - pos_id
  "/store/{id}":
    get:
      summary: Retrieves a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: store found
          content:
            application/json:
              example:
                status_code: 0
                store:
                  id: 1
                  merchant_id: '9999999'
                  name: 街口測試1
                  pos_id: '1'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
    patch:
      summary: Update a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: update store
          content:
            application/json:
              example:
                status_code: 0
                store:
                  id: 1
                  merchant_id: '9999999'
                  name: 街口測試1
                  pos_id: '1'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_id:
                  type: string
                name:
                  type: string
                pos_id:
                  type: string
    delete:
      summary: Delete a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: delete store
          content:
            application/json:
              example:
                status_code: 0
servers:
- url: http://{defaultHost}:3000
  variables:
    defaultHost:
      default: localhost
