---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/store":
    get:
      summary: Retrieves all stores
      tags:
      - Stores
      responses:
        '200':
          description: store found
          content:
            application/json:
              example:
                status_code: 0
                stores:
                - id: 1
                  merchant_id: '123'
                  store_id: '123'
                  name: '123'
                  pos_id: '123'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
                - id: 2
                  merchant_id: '33344'
                  store_id: '123'
                  name: '123'
                  pos_id: '123'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
  "/store/{id}":
    get:
      summary: Retrieves a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: store found
          content:
            application/json:
              example:
                id: 1
                merchant_id: xxxx
                name: weiby
                pos_id: 22xxx
servers:
- url: http://{defaultHost}:3000
  variables:
    defaultHost:
      default: localhost
