---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/store/{id}":
    get:
      summary: Retrieves a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: store found
          content:
            application/json:
              example:
                id: 1
                merchant_id: xxxx
                name: weiby
                pos_id: 22xxx
servers:
- url: http://{defaultHost}:3000
  variables:
    defaultHost:
      default: localhost
