---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/cancel":
    post:
      summary: 取消,當POS端送出付款交易(Payment)後，與街口連線異常或交易逾時，可發送取消交易(Cancel)，取消該筆付款。
      tags:
      - Cancel
      parameters: []
      responses:
        '200':
          description: payment response
          content:
            application/json:
              example:
                status_code: 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_trade_number:
                  type: string
                  description: 商店端交易序號(付款流水號)(需與 Payment 相同)
                  example: '20200090444511'
                merchant_id:
                  type: string
                  description: 特店代碼
                  example: '9999999'
                merchant_key:
                  type: string
                  example: 2AA6B9B6F9C64247ABB2677B6AF2C896
              required:
              - merchant_id
              - merchant_key
  "/inquiry":
    post:
      summary: 付款查詢或退款查詢
      tags:
      - Inquiry
      parameters: []
      responses:
        '200':
          description: inquiry response
          content:
            application/json:
              example:
                status_code: 2
                response:
                  raw:
                    status: 200
                    body: '{"MerchantID":"9999999","StoreID":"1234","GatewayTradeNo":"","MerchantTradeNo":"1234555555","PosID":"1","StatusCode":"916","StatusDesc":"查無此訂單"}'
                    response_headers:
                      server: nginx/1.18.0
                      date: Tue, 24 Aug 2021 10:03:20 GMT
                      content-type: application/json
                      transfer-encoding: chunked
                      connection: keep-alive
                  MerchantID: '9999999'
                  StoreID: '1234'
                  GatewayTradeNo: ''
                  MerchantTradeNo: '1234555555'
                  PosID: '1'
                  StatusCode: '916'
                  StatusDesc: 查無此訂單
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_trade_number:
                  type: string
                  description: 商店端交易序號(付款流水號)
                  example: '1234555555'
                merchant_id:
                  type: string
                  description: 特店代碼
                  example: '9999999'
                merchant_key:
                  type: string
                  example: 2AA6B9B6F9C64247ABB2677B6AF2C896
                inquiry_type:
                  type: string
                  description: 付款查詢請帶"P" 退款查詢請帶"R"
                  example: R
                store_id:
                  type: string
                  description: 商店編號
                  example: '1234'
                pos_id:
                  type: string
                  description: POS機號
                  example: '1'
                pos_trade_time:
                  type: string
                  description: POS 端交易日期時間, 格式:yyyy/MM/dd HH:mm:ss
                  example: 2020/08/01 10:05:11
              required:
              - merchant_trade_number
              - merchant_id
              - merchant_key
              - inquiry_type
              - store_id
              - pos_id
              - pos_trade_time
  "/payment":
    post:
      summary: 付款
      tags:
      - Payment
      parameters: []
      responses:
        '200':
          description: payment response
          content:
            application/json:
              example:
                status_code: 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_id:
                  type: string
                  description: 特店代碼
                  example: '9999999'
                merchant_key:
                  type: string
                  example: 2AA6B9B6F9C64247ABB2677B6AF2C896
                card_token:
                  type: string
                  description: 支付條碼
                  example: 22C333334444455555
                store_id:
                  type: string
                  description: 商店編號
                  example: '1234'
                store_name:
                  type: string
                  description: 商店名稱
                  example: 街口測試
                merchant_trade_number:
                  type: string
                  description: 商店端交易序號(付款流水號)
                  example: '1234555555'
                pos_id:
                  type: string
                  description: POS機號
                  example: '1'
                pos_trade_time:
                  type: string
                  description: POS 端交易日期時間, 格式:yyyy/MM/dd HH:mm:ss
                  example: 2020/08/01 10:05:11
                trade_amount:
                  type: integer
                  description: 實際消費金額
                  example: 10
                un_redeem_amount:
                  type: integer
                  description: 不可折抵金額, 若無請放 0
                  example: 0
              required:
              - merchant_id
              - merchant_key
              - card_token
              - store_id
              - store_name
              - merchant_trade_number
              - pos_id
              - pos_trade_time
              - trade_amount
              - un_redeem_amount
  "/refund":
    post:
      summary: 退款
      tags:
      - Refund
      parameters: []
      responses:
        '200':
          description: payment response
          content:
            application/json:
              example:
                status_code: 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_trade_number:
                  type: string
                  description: 商店端交易序號(退款流水號),需為唯一值，不可重複
                  example: '1234555555'
                merchant_id:
                  type: string
                  description: 特店代碼
                  example: '9999999'
                merchant_key:
                  type: string
                  example: 2AA6B9B6F9C64247ABB2677B6AF2C896
                store_id:
                  type: string
                  description: 商店編號
                  example: '1234'
                store_name:
                  type: string
                  description: 商店名稱
                  example: 街口測試
                pos_id:
                  type: string
                  description: POS機號
                  example: '1'
                pos_trade_time:
                  type: string
                  description: POS 端交易日期時間, 格式:yyyy/MM/dd HH:mm:ss
                  example: 2020/08/01 10:05:11
                trade_no:
                  type: string
                  description: 原街口端交易序號, POS 端需比對客戶退款單號是否正確
                  example: J0065220121081800001
                trade_amount:
                  type: integer
                  description: 退款金額
                  example: 10
              required:
              - merchant_trade_number
              - merchant_id
              - merchant_key
              - store_id
              - store_name
              - pos_id
              - pos_trade_time
              - trade_amount
  "/store":
    get:
      summary: Retrieves all stores
      tags:
      - Stores
      responses:
        '200':
          description: store found
          content:
            application/json:
              example:
                status_code: 0
                stores:
                - id: 1
                  merchant_id: '9999999'
                  store_id: '1'
                  name: 街口測試1
                  pos_id: '1'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
                - id: 2
                  merchant_id: '9999999'
                  store_id: '2'
                  name: 街口測試2
                  pos_id: '2'
                  created_at: '2021-08-21T22:47:53.517Z'
                  updated_at: '2021-08-21T22:47:53.517Z'
    post:
      summary: Create a store
      tags:
      - Stores
      parameters: []
      responses:
        '200':
          description: store created
          content:
            application/json:
              example:
                status_code: 0
                store:
                  id: 1
                  merchant_id: '9999999'
                  name: 街口測試1
                  pos_id: '1'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_id:
                  type: string
                  example: '9999999'
                  description: 特店代碼,唯一碼
                name:
                  type: string
                  example: 拉亞漢堡
                pos_id:
                  type: string
                  example: '1'
                  description: POS機號
              required:
              - merchant_id
              - name
              - pos_id
  "/store/{id}":
    get:
      summary: Retrieves a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        description: 商店ID流水號
        example: '1'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: store found
          content:
            application/json:
              example:
                status_code: 0
                store:
                  id: 1
                  merchant_id: '9999999'
                  name: 街口測試1
                  pos_id: '1'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
    patch:
      summary: Update a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        description: 商店ID流水號
        example: '1'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: update store
          content:
            application/json:
              example:
                status_code: 0
                store:
                  id: 1
                  merchant_id: '9999999'
                  name: 街口測試1
                  pos_id: '1'
                  created_at: '2021-08-20T22:47:53.517Z'
                  updated_at: '2021-08-20T22:47:53.517Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_id:
                  type: string
                  example: '9999999'
                  description: 特店代碼
                name:
                  type: string
                  example: 拉亞漢堡
                pos_id:
                  type: string
                  example: '1'
                  description: POS機號
    delete:
      summary: Delete a store
      tags:
      - Stores
      parameters:
      - name: id
        in: path
        description: 商店ID流水號
        example: '1'
        required: true
        schema:
          type: string
      responses:
        '200':
          description: delete store
          content:
            application/json:
              example:
                status_code: 0
servers:
- url: http://{defaultHost}:3000
  variables:
    defaultHost:
      default: localhost
